# Generated by Django 2.2.3 on 2019-07-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField(blank=True, verbose_name='Идентификатор дома')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес дома')),
                ('breakdown', models.CharField(max_length=50, verbose_name='Поломка')),
                ('challenge_accepted', models.DateField(verbose_name='Дата принятия вызова')),
                ('challenge_done', models.DateField(verbose_name='Дата выполнения')),
            ],
            options={
                'verbose_name': 'Заявка на выполение работы',
                'verbose_name_plural': 'Заявки на выполнение работы',
            },
        ),
    ]
