# Generated by Django 2.2.3 on 2019-07-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190706_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tsj_id',
            field=models.BigIntegerField(default=-1, verbose_name='Идентификатор ТСЖ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
