# Generated by Django 2.2.3 on 2019-07-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190706_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='done', max_length=20, verbose_name='Статус выполнения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='breakdown',
            field=models.CharField(max_length=50, verbose_name='Категория поломки'),
        ),
    ]
