# Generated by Django 2.2.3 on 2019-07-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190706_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='challenge_done',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
