# Generated by Django 2.2.3 on 2019-07-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190706_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='Тестовая услуга', max_length=100, verbose_name='Услуга'),
        ),
    ]
